# Generated by Django 4.1.7 on 2023-06-18 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_top_options_alter_works_options_and_more'),
        ('crm', '0006_alter_order_order_works'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_works',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.works', verbose_name='Работа'),
        ),
    ]
